/*
 * Full array of US restaurant categories, processed from https://www.yelp.com/developers/documentation/v3/all_category_list
 */

module.exports =
[{"alias":"afghani","title":"Afghan"},{"alias":"african","title":"African"},{"alias":"andalusian","title":"Andalusian"},
{"alias":"arabian","title":"Arabian"},{"alias":"argentine","title":"Argentine"},{"alias":"armenian","title":"Armenian"},
{"alias":"asianfusion","title":"Asian Fusion"},{"alias":"asturian","title":"Asturian"},{"alias":"australian","title":"Australian"},
{"alias":"austrian","title":"Austrian"},{"alias":"baguettes","title":"Baguettes"},{"alias":"bangladeshi","title":"Bangladeshi"},
{"alias":"bangladeshi","title":"Bangladesh"},{"alias":"basque","title":"Basque"},{"alias":"bavarian","title":"Bavarian"},
{"alias":"bbq","title":"Barbeque"},{"alias":"bbq","title":"BBQ"},{"alias":"beergarden","title":"Beer Garden"},
{"alias":"beerhall","title":"Beer Hall"},{"alias":"beisl","title":"Beisl"},{"alias":"belgian","title":"Belgian"},
{"alias":"bistros","title":"Bistros"},{"alias":"bistros","title":"Bistro"},{"alias":"blacksea","title":"Black Sea"},
{"alias":"brasseries","title":"Brasseries"},{"alias":"brazilian","title":"Brazilian"},{"alias":"breakfast_brunch","title":"Breakfast & Brunch"},
{"alias":"breakfast_brunch","title":"Breakfast and Brunch"},{"alias":"breakfast_brunch","title":"Brunch"},
{"alias":"british","title":"British"},{"alias":"buffets","title":"Buffets"},{"alias":"buffets","title":"Buffet"},
{"alias":"bulgarian","title":"Bulgarian"},{"alias":"burgers","title":"Burgers"},{"alias":"burgers","title":"Burger"},
{"alias":"burmese","title":"Burmese"},{"alias":"cafes","title":"Cafes"},{"alias":"cafes","title":"Cafe"},
{"alias":"cafeteria","title":"Cafeteria"},{"alias":"cajun","title":"Creole"},{"alias":"cajun","title":"Cajun"},
{"alias":"cambodian","title":"Cambodian"},{"alias":"canteen","title":"Canteen"},{"alias":"caribbean","title":"Caribbean"},
{"alias":"catalan","title":"Catalan"},{"alias":"cheesesteaks","title":"Cheesesteaks"},{"alias":"cheesesteaks","title":"Cheesesteak"},
{"alias":"chicken_wings","title":"Chicken Wings"},{"alias":"chicken_wings","title":"Wings"},
{"alias":"chicken_wings","title":"Chicken Wing"},{"alias":"chicken_wings","title":"Wing"},
{"alias":"chickenshop","title":"Chicken Shop"},{"alias":"chilean","title":"Chilean"},{"alias":"chinese","title":"Chinese"},
{"alias":"comfortfood","title":"Comfort Food"},{"alias":"comfortfood","title":"Comfort"},
{"alias":"corsican","title":"Corsican"},{"alias":"creperies","title":"Creperies"},{"alias":"cuban","title":"Cuban"},
{"alias":"currysausage","title":"Curry Sausage"},{"alias":"cypriot","title":"Cypriot"},{"alias":"czech","title":"Czech"},
{"alias":"czechslovakian","title":"Czech Slovakian"},{"alias":"danish","title":"Danish"},
{"alias":"delis","title":"Delis"},{"alias":"delis","title":"Deli"},{"alias":"diners","title":"Diner"},{"alias":"diners","title":"Diners"},
{"alias":"dinnertheater","title":"Dinner Theater"},{"alias":"dumplings","title":"Dumplings"},{"alias":"dumplings","title":"Dumpling"},
{"alias":"eastern_european","title":"Eastern European"},{"alias":"eltern_cafes","title":"Parent Cafes"},
{"alias":"ethiopian","title":"Ethiopian"},{"alias":"filipino","title":"Filipino"},{"alias":"fischbroetchen","title":"Fischbroetchen"},
{"alias":"fishnchips","title":"Fish & Chips"},{"alias":"fishnchips","title":"Fish and Chips"},
{"alias":"flatbread","title":"Flatbread"},{"alias":"fondue","title":"Fondue"},{"alias":"food_court","title":"Food Court"},
{"alias":"foodstands","title":"Food Stands"},{"alias":"foodstands","title":"Food Stand"},
{"alias":"freiduria","title":"Freiduria"},{"alias":"french","title":"French"},{"alias":"galician","title":"Galician"},
{"alias":"gastropubs","title":"Gastropubs"},{"alias":"gastropubs","title":"Gastropub"},
{"alias":"georgian","title":"Georgian"},{"alias":"german","title":"German"},{"alias":"giblets","title":"Giblets"},
{"alias":"gluten_free","title":"Gluten-Free"},{"alias":"gluten_free","title":"Gluten Free"},{"alias":"gluten_free","title":"No Gluten"},
{"alias":"greek","title":"Greek"},{"alias":"halal","title":"Halal"},{"alias":"hawaiian","title":"Hawaiian"},
{"alias":"heuriger","title":"Heuriger"},{"alias":"himalayan","title":"Himalayan"},{"alias":"himalayan","title":"Nepalese"},
{"alias":"hkcafe","title":"Hong Kong Style Cafe"},{"alias":"hkcafe","title":"Hong Kong"},
{"alias":"hotdog","title":"Hot Dogs"},{"alias":"hotdog","title":"Hot Dog"},{"alias":"hotdogs","title":"Fast Food"},
{"alias":"hotpot","title":"Hot Pot"},{"alias":"hungarian","title":"Hungarian"},{"alias":"iberian","title":"Iberian"},
{"alias":"indonesian","title":"Indonesian"},{"alias":"indpak","title":"Indian"},{"alias":"international","title":"International"},
{"alias":"irish","title":"Irish"},{"alias":"island_pub","title":"Island Pub"},{"alias":"israeli","title":"Israeli"},
{"alias":"italian","title":"Italian"},{"alias":"japanese","title":"Japanese"},{"alias":"jewish","title":"Jewish"},
{"alias":"kebab","title":"Kebab"},{"alias":"kopitiam","title":"Kopitiam"},{"alias":"korean","title":"Korean"},
{"alias":"kosher","title":"Kosher"},{"alias":"kurdish","title":"Kurdish"},{"alias":"laos","title":"Laos"},
{"alias":"laotian","title":"Laotian"},{"alias":"latin","title":"Latin American"},{"alias":"lyonnais","title":"Lyonnais"},
{"alias":"malaysian","title":"Malaysian"},{"alias":"meatballs","title":"Meatballs"},{"alias":"meatballs","title":"Meatball"},
{"alias":"mediterranean","title":"Mediterranean"},{"alias":"mexican","title":"Mexican"},{"alias":"mideastern","title":"Middle Eastern"},
{"alias":"milkbars","title":"Milk Bars"},{"alias":"milkbars","title":"Milk Bar"},{"alias":"modern_australian","title":"Modern Australian"},
{"alias":"modern_european","title":"Modern European"},{"alias":"mongolian","title":"Mongolian"},{"alias":"moroccan","title":"Moroccan"},
{"alias":"newamerican","title":"American"},{"alias":"newcanadian","title":"Canadian"},{"alias":"newmexican","title":"New Mexican Cuisine"},
{"alias":"newzealand","title":"New Zealand"},{"alias":"nicaraguan","title":"Nicaraguan"},{"alias":"nightfood","title":"Night Food"},
{"alias":"nikkei","title":"Nikkei"},{"alias":"noodles","title":"Noodles"},{"alias":"noodles","title":"Noodle"},
{"alias":"norcinerie","title":"Norcinerie"},{"alias":"norwegian","title":"Norwegian"},{"alias":"norwegian","title":"Traditional Norwegian"},
{"alias":"opensandwiches","title":"Open Sandwiches"},{"alias":"opensandwiches","title":"Open Sandwich"},
{"alias":"oriental","title":"Oriental"},{"alias":"pakistani","title":"Pakistani"},
{"alias":"panasian","title":"Pan Asian"},{"alias":"parma","title":"Parma"},
{"alias":"persian","title":"Iranian"},{"alias":"persian","title":"Persian"},{"alias":"peruvian","title":"Peruvian"},
{"alias":"pfcomercial","title":"Comercial"},{"alias":"pita","title":"Pita"},{"alias":"pizza","title":"Pizza"},
{"alias":"polish","title":"Polish"},{"alias":"popuprestaurants","title":"Pop-Up Restaurants"},
{"alias":"portuguese","title":"Portuguese"},{"alias":"potatoes","title":"Potatoes"},{"alias":"poutineries","title":"Poutineries"},
{"alias":"poutineries","title":"Poutine"},{"alias":"pubfood","title":"Pub Food"},{"alias":"pubfood","title":"Pub"},
{"alias":"raw_food","title":"Raw Food"},{"alias":"raw_food","title":"Live Food"},{"alias":"riceshop","title":"Rice"},
{"alias":"romanian","title":"Romanian"},{"alias":"rotisserie_chicken","title":"Rotisserie Chicken"},
{"alias":"rumanian","title":"Rumanian"},{"alias":"russian","title":"Russian"},{"alias":"salad","title":"Salad"},
{"alias":"sandwiches","title":"Sandwiches"},{"alias":"sandwiches","title":"Sandwich"},{"alias":"scandinavian","title":"Scandinavian"},
{"alias":"schnitzel","title":"Schnitzel"},{"alias":"scottish","title":"Scottish"},{"alias":"seafood","title":"Seafood"},
{"alias":"serbocroatian","title":"Serbo Croatian"},{"alias":"signature_cuisine","title":"Signature Cuisine"},
{"alias":"singaporean","title":"Singaporean"},{"alias":"singaporean","title":"Singapore"},{"alias":"slovakian","title":"Slovakian"},
{"alias":"soulfood","title":"Soul Food"},{"alias":"soup","title":"Soup"},{"alias":"southern","title":"Southern"},
{"alias":"spanish","title":"Spanish"},{"alias":"srilankan","title":"Sri Lankan"},
{"alias":"steak","title":"Steakhouses"},{"alias":"steak","title":"Steakhouse"},{"alias":"steak","title":"Steak"},
{"alias":"sud_ouest","title":"French Southwest"},{"alias":"supperclubs","title":"Supper Clubs"},
{"alias":"sushi","title":"Sushi Bars"},{"alias":"sushi","title":"Sushi Bar"},{"alias":"sushi","title":"Sushi"},
{"alias":"swabian","title":"Swabian"},{"alias":"swedish","title":"Swedish"},{"alias":"swissfood","title":"Swiss Food"},
{"alias":"swissfood","title":"Swiss"},{"alias":"syrian","title":"Syrian"},{"alias":"tabernas","title":"Tabernas"},
{"alias":"taiwanese","title":"Taiwanese"},{"alias":"tapas","title":"Tapas Bars"},{"alias":"tapas","title":"Tapas Bar"},
{"alias":"tapasmallplates","title":"Tapas"},{"alias":"tapasmallplates","title":"Small Plates"},
{"alias":"tavolacalda","title":"Tavola Calda"},{"alias":"tex-mex","title":"Tex-Mex"},{"alias":"tex-mex","title":"Tex Mex"},
{"alias":"thai","title":"Thai"},{"alias":"tradamerican","title":"Traditional American"},
{"alias":"traditional_swedish","title":"Traditional Swedish"},{"alias":"trattorie","title":"Trattorie"},
{"alias":"turkish","title":"Turkish"},{"alias":"ukrainian","title":"Ukrainian"},{"alias":"uzbek","title":"Uzbek"},
{"alias":"vegan","title":"Vegan"},{"alias":"vegetarian","title":"Vegetarian"},{"alias":"venison","title":"Venison"},
{"alias":"vietnamese","title":"Vietnamese"},{"alias":"vietnamese","title":"Pho"},{"alias":"waffles","title":"Waffles"},
{"alias":"waffles","title":"Waffle"},{"alias":"wok","title":"Wok"},{"alias":"wraps","title":"Wraps"},
{"alias":"wraps","title":"Wrap"},{"alias":"yugoslav","title":"Yugoslav"}];
